@startuml
'context-view'

package Классификатор{
  usecase "Установить параметры обучения" as set_params
  usecase "Загрузить данные для обучения" as set_test_data
  usecase "Обучить модель" as train_model
  usecase "Тестировать классификатор" as test_model
  usecase "Оставить заявку на кредит" as request_credit
}

actor "Работник банка" as specialist
actor "Клиент" as client

specialist --> set_test_data
specialist --> set_params
specialist --> train_model
specialist --> test_model

client --> request_credit
@enduml