@startuml
'physical-view'

node Клиент {
  [Клиентское приложение]
}

node Сервер {
  [Веб-сервер]
  [Классификатор]
}

[Веб-сервер] ..> [Классификатор]
HTTPS - [Веб-сервер]
[Клиентское приложение] --> HTTPS

@enduml