@startuml
'process-view'

start

:Проверка параметров и экземпляра клиента;

if (Данные прошли проверку) then (да)
    :Разделить полученные данные;
    :Сохранить данные для обучения;
    :Обучить модель;
    stop
else (нет)
    :Отправить ответ с ошибкой;
    stop
endif

@enduml