@startuml
'context-view'

package Классификатор{
  usecase "Установить параметры обучения" as set_params
  usecase "Обучить модель" as train_model
  usecase "Загрузить тестовые данные" as set_test_data
  usecase "Классифицировать объект" as classify_object
}

actor "Специалист по машинному обучению" as specialist
actor "Пользователь" as user

specialist --> set_test_data
specialist --> set_params
specialist --> train_model
specialist --> classify_object


user --> classify_object
@enduml