@startuml
'development-view'

package Классификатор {
  [Функции представления]
  [Модели данных]
  [Тесты]
}

  [Функции представления] ..> [flask]
  [Тесты] ..> [pytest]
  [Тесты] ..> [tox]
  [Функции представления] ..> [Модели данных]
  [Тесты] ..> [Модели данных]
  [Тесты] ..> [Функции представления]
@enduml