@startuml
'process-view'

start

:Проверка имени и экземпляров образцов;

if (Данные прошли проверку) then (да)
    :Разделить полученные образцы;
    :Сохранить данные для обучения;
    stop
else (нет)
    :Отправить ответ с ошибкой;
    stop
endif

@enduml